/**
 * KYRO Dashboard - Main Dashboard Implementation
 * Handles KPI cards, charts, real-time alerts, and system monitoring
 */

const Dashboard = {
    charts: {},
    realTimeUpdates: true,
    updateInterval: 30000, // 30 seconds
    
    init() {
        this.loadDashboard();
        this.setupEventListeners();
        this.startRealTimeUpdates();
    },
    
    async loadDashboard() {
        showLoading("#mainContent", "Loading dashboard...");
        
        try {
            const dashboardHtml = await this.getDashboardHTML();
            $("#mainContent").html(dashboardHtml);
            
            // Load data and initialize components
            await Promise.all([
                this.loadKPIs(),
                this.initializeCharts()
            ]);
            
        } catch (error) {
            console.error("Dashboard load error:", error);
            $("#mainContent").html(`
                <div class="alert alert-danger" role="alert">
                    <h4 class="alert-heading">Dashboard Load Error</h4>
                    <p>Failed to load dashboard data. Please refresh the page or contact support.</p>
                    <button class="btn btn-outline-danger" onclick="Dashboard.loadDashboard()">
                        <i class="fas fa-redo me-2"></i>Retry
                    </button>
                </div>
            `);
        }
    },
    
    
    getDashboardHTML() {
        return `
            <div class="kyro-dashboard-container kyro-dashboard-grid">
                <!-- Review Case Volume -->
                <section class="aml-card">
                    <h2>Review Case Volume</h2>
                    <p class="aml-subtitle">Overview of Reviews</p>
                    
                    <div class="aml-legend aml-chart-legend">
                        <span class="aml-dot orange"></span> <span id="caseVolumePeriodText">+913 Last period</span>
                    </div>
                    
                    <div class="aml-chart">
                        <div class="aml-gridline"><span>100</span></div>
                        <div class="aml-gridline"><span>75</span></div>
                        <div class="aml-gridline"><span>50</span></div>
                        <div class="aml-gridline"><span>25</span></div>
                        <div class="aml-gridline"><span>0</span></div>
                        
                        <div class="aml-bars" id="volumeBars">
                            <!-- Bars will be generated by JS -->
                        </div>
                    </div>
                </section>

                <!-- Customer Risk Profile -->
                <section class="aml-card aml-donut-card">
                    <h2>Customer Risk Profile</h2>
                    <p class="aml-subtitle">Overview of Customer Risk</p>
                    
                    <div class="aml-donut-wrap">
                        <div class="aml-donut" id="riskDonut" role="img" aria-label="Customer risk distribution"></div>
                    </div>
                    
                    <div class="aml-donut-legend">
                        <span class="aml-legend">
                            <span class="aml-dot orange"></span> 
                            <span id="highRiskLegend">High Risk - (90.0%)</span>
                        </span>
                        <span class="aml-legend">
                            <span class="aml-dot dark"></span> 
                            <span id="lowMidLegend">Low/Mid - (10.0%)</span>
                        </span>
                    </div>
                </section>
            </div>
            
            <div class="kyro-dashboard-container" style="padding-top: 0;">
                <!-- Existing dashboard content below -->

                <!-- Behavior Pattern Trends -->
                <div class="row mb-4">
                    <div class="col-12">
                        <div class="card p-4" style="border-radius: 8px; border: 1px solid #E0E0E0; box-shadow: none; background: white;">
                            <div class="mb-4">
                                <h5 class="fw-bold mb-1" style="font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1rem; color: #1a1a1a;">Behavior Pattern Trends</h5>
                                <p class="text-xs text-muted mb-0" style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #888888;">Overview of behaviour</p>
                            </div>
                            <div style="height: 240px; width: 100%; position: relative;">
                                <canvas id="behaviorTrendsChart"></canvas>
                            </div>
                            <div class="d-flex align-items-center justify-content-center gap-4 mt-4">
                                <div class="d-flex align-items-center gap-2">
                                    <div style="width: 20px; height: 3px; background-color: #2D3748; border-radius: 2px;"></div>
                                    <span class="text-xs text-muted" style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #666666;">Detected</span>
                                </div>
                                <div class="d-flex align-items-center gap-2">
                                    <div style="width: 20px; height: 3px; background-color: #FF8D28; border-radius: 2px;"></div>
                                    <span class="text-xs text-muted" style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #666666;">Flagged</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Bottom Row - Case Status Overview, Behavioral Flags, Transaction Overview -->
                <div class="row g-4 mb-4">
                    <!-- Case Status Overview -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card p-4 h-100" style="border-radius: 8px; border: 1px solid #E0E0E0; box-shadow: none; background: white;">
                            <div class="mb-3">
                                <h5 class="fw-bold mb-1" style="font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1rem; color: #1a1a1a;">Case Status Overview</h5>
                                <p class="text-xs text-muted mb-0" style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #888888;">Every month</p>
                            </div>
                            <div style="height: 180px; position: relative;">
                                <canvas id="caseStatusChart"></canvas>
                            </div>
                            <div class="mt-4">
                                <div class="d-flex justify-content-between align-items-center mb-2 pb-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <div class="d-flex align-items-center gap-2">
                                        <span style="width: 8px; height: 8px; background-color: #22c55e; border-radius: 50%;"></span>
                                        <span style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Open cases</span>
                                    </div>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">106</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center mb-2 pb-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <div class="d-flex align-items-center gap-2">
                                        <span style="width: 8px; height: 8px; background-color: #f59e0b; border-radius: 50%;"></span>
                                        <span style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">In Review</span>
                                    </div>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">4</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center mb-2 pb-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <div class="d-flex align-items-center gap-2">
                                        <span style="width: 8px; height: 8px; background-color: #3b82f6; border-radius: 50%;"></span>
                                        <span style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Resolved</span>
                                    </div>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">311</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="d-flex align-items-center gap-2">
                                        <span style="width: 8px; height: 8px; background-color: #ef4444; border-radius: 50%;"></span>
                                        <span style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Escalated</span>
                                    </div>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">70</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Behavioral Flags by Pattern Type -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card p-4 h-100" style="border-radius: 8px; border: 1px solid #E0E0E0; box-shadow: none; background: white;">
                            <div class="mb-3">
                                <h5 class="fw-bold mb-1" style="font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1rem; color: #1a1a1a;">Behavioral Flags by Pattern Type</h5>
                                <p class="text-xs text-muted mb-0" style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #888888;">Transaction-wise</p>
                            </div>
                            <div class="mt-3">
                                <div class="d-flex justify-content-between align-items-center py-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <span style="font-size: 12px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Velocity Spike</span>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">119</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center py-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <span style="font-size: 12px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Geographic Shift</span>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">89</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center py-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <span style="font-size: 12px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Complexity Shift</span>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">119</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center py-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <span style="font-size: 12px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Counterparty Changes</span>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">89</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center py-2" style="border-bottom: 1px solid #F0F0F0;">
                                    <span style="font-size: 12px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Inactive Reactivation</span>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">89</span>
                                </div>
                                <div class="d-flex justify-content-between align-items-center py-2">
                                    <span style="font-size: 12px; font-family: 'Plus Jakarta Sans', sans-serif; color: #1a1a1a;">Threshold Breach</span>
                                    <span class="fw-bold" style="font-size: 13px; color: #1a1a1a;">89</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Transaction Overview -->
                    <div class="col-lg-4 col-md-6">
                        <div class="card p-4 h-100" style="border-radius: 8px; border: 1px solid #1a1a1a; background: #1a1a1a; box-shadow: none;">
                            <div class="mb-3">
                                <h5 class="fw-bold mb-1" style="font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1rem; color: #FF8D28;">Transaction Overview</h5>
                                <p class="text-xs mb-0" style="font-size: 11px; font-family: 'Plus Jakarta Sans', sans-serif; color: #22c55e;">Average sales</p>
                            </div>
                            <div class="mt-4">
                                <div class="d-flex align-items-center gap-3 mb-4">
                                    <div style="width: 48px; height: 48px; background: #2a2a2a; border-radius: 8px; display: flex; align-items: center; justify-content: center;">
                                        <i class="fas fa-th" style="color: #FF8D28; font-size: 18px;"></i>
                                    </div>
                                    <div class="flex-grow-1">
                                        <p class="mb-0" style="font-size: 12px; color: #94a3b8; font-family: 'Plus Jakarta Sans', sans-serif;">Total Transaction</p>
                                        <h4 id="txOverviewCount" class="mb-0 fw-bold" style="color: white; font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1.4rem;">20,202</h4>
                                    </div>
                                </div>
                                <div class="d-flex align-items-center gap-3 mb-4">
                                    <div style="width: 48px; height: 48px; background: #2a2a2a; border-radius: 8px; display: flex; align-items: center; justify-content: center;">
                                        <i class="fas fa-th" style="color: #FF8D28; font-size: 18px;"></i>
                                    </div>
                                    <div class="flex-grow-1">
                                        <p class="mb-0" style="font-size: 12px; color: #94a3b8; font-family: 'Plus Jakarta Sans', sans-serif;">Total Volume</p>
                                        <h4 id="txOverviewVolume" class="mb-0 fw-bold" style="color: white; font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1.4rem;">$254,161,837.07</h4>
                                    </div>
                                </div>
                                <div class="d-flex align-items-center gap-3">
                                    <div style="width: 48px; height: 48px; background: #2a2a2a; border-radius: 8px; display: flex; align-items: center; justify-content: center;">
                                        <i class="fas fa-th" style="color: #FF8D28; font-size: 18px;"></i>
                                    </div>
                                    <div class="flex-grow-1">
                                        <p class="mb-0" style="font-size: 12px; color: #94a3b8; font-family: 'Plus Jakarta Sans', sans-serif;">Average Amount</p>
                                        <h4 id="txOverviewAverage" class="mb-0 fw-bold" style="color: white; font-family: 'Plus Jakarta Sans', sans-serif; font-size: 1.4rem;">₹12,581.02</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                                <div class="d-flex align-items-center justify-content-between p-3 rounded-lg" style="background: rgba(255, 255, 255, 0.1);">
                                    <div class="d-flex align-items-center gap-3">
                                        <div class="p-2 rounded-lg" style="background: rgba(255, 255, 255, 0.2); width: 38px; height: 38px; display: flex; align-items: center; justify-content: center;">
                                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" style="width: 20px; height: 20px;">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                                            </svg>
                                        </div>
                                        <div>
                <!-- Take Action Section -->
                <div class="take-action-wrapper" style="padding: 0; max-width: 1200px; margin: 0 auto;">
                    <div class="text-center my-5" style="padding: 0 16px;">
                        <h2 class="figma-heading text-2xl mb-2">Take Action</h2>
                        <p class="figma-text-gray">Quick access to critical review workflows</p>
                    </div>

                    <div class="container" style="max-width: 1200px; padding: 0 16px;">
                        <div class="row g-4 mb-5" style="margin: 0; width: 100%; display: flex; justify-content: center; align-items: stretch;">
                            <!-- Review Cases Card -->
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4" style="padding: 0 12px; display: flex;">
                                <div class="figma-action-card h-100" onclick="App.navigateTo('cases')" style="width: 100%; flex: 1;">
                                    <h3 class="figma-text-orange font-medium text-lg mb-2">Review Cases</h3>
                                    <p class="figma-text-gray mb-4">Process and resolve all flagged cases</p>
                                    <div class="figma-button d-inline-flex px-4 py-2 mx-auto">
                                        <span class="text-white" id="takeActionCasesVal">0 Active</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Periodic Reviews Card -->
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4" style="padding: 0 12px; display: flex;">
                                <div class="figma-action-card-dark h-100" onclick="App.navigateTo('periodic-reviews')" style="width: 100%; flex: 1;">
                                    <h3 class="figma-text-orange font-medium text-lg mb-2">Periodic Reviews</h3>
                                    <p class="figma-text-white mb-4">Schedule and manage time-based customer reviews</p>
                                    <div class="figma-button d-inline-flex px-4 py-2 mx-auto">
                                        <span class="text-white" id="takeActionReviewsVal">0 Pending</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Behavioral Patterns Card -->
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4" style="padding: 0 12px; display: flex;">
                                <div class="figma-action-card h-100" onclick="App.navigateTo('patterns')" style="width: 100%; flex: 1;">
                                    <h3 class="figma-text-orange font-medium text-lg mb-2">Behavioral Patterns</h3>
                                    <p class="figma-text-gray mb-4">Analyze and investigate behavioral anomalies</p>
                                    <div class="figma-button d-inline-flex px-4 py-2 mx-auto">
                                        <span class="text-white" id="takeActionPatternsVal">0 Detected</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Bottom Left Button: Back to Home -->
                <div class="position-fixed take-action-back-btn" style="bottom: 20px; left: 20px; z-index: 1000;">
                    <a href="/" class="btn fw-bold px-4 py-2" style="background-color: #FF8C42; color: #ffffff; border-radius: 6px; box-shadow: 0 4px 12px rgba(255, 140, 66, 0.3); font-family: 'Plus Jakarta Sans', sans-serif; font-size: 14px; text-decoration: none;">
                        Back to Home
                    </a>
                </div>
            </div>
        `;
    },
    
    async loadKPIs() {
        try {
            const data = await API.get(API.endpoints.kpis);
            
            // Keep notification updates intact
            $("#notificationBadge").text(data.pending_alerts);
            $("#sidebarAlertCount").text(data.pending_alerts);

            // Update Transaction Overview card values
            const formattedTotalTx = Number(data.total_transactions || 0).toLocaleString();
            const formattedTotalVol = '$' + Number(data.total_volume || 0).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2});
            const formattedAvgAmt = '$' + Number(data.avg_amount || 0).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2});
            
            $("#txOverviewCount").text(formattedTotalTx);
            $("#txOverviewVolume").text(formattedTotalVol);
            $("#txOverviewAverage").text(formattedAvgAmt);

            // Update Take Action values
            $("#takeActionCasesVal").text(`${data.pending_alerts || 0} Active`);

            // Set periodic reviews count based on mockup reviews data if defined, otherwise 288
            const periodicCount = (window.PeriodicReviews && window.PeriodicReviews.reviewsData && window.PeriodicReviews.reviewsData.length) || 288;
            $("#takeActionReviewsVal").text(`${periodicCount} Pending`);
            
            // Load patterns data
            try {
                const patternData = await API.get("/dashboard/patterns");
                if (patternData) {
                    // Update Behavioral Patterns Take Action count
                    $("#takeActionPatternsVal").text(`${patternData.total_pattern_hits || 0} Detected`);
                    
                    // Update Behavioral Flags List
                    if (patternData.patterns) {
                        let html = '';
                        patternData.patterns.forEach((pattern, index) => {
                            const isLast = index === patternData.patterns.length - 1;
                            const borderStyle = isLast ? '' : 'style="border-bottom: 1px solid rgba(124, 143, 172, 0.08);"';
                            html += `
                                <div class="d-flex justify-content-between align-items-center py-2" ${borderStyle}>
                                    <span class="figma-text-gray text-sm">${pattern.label}</span>
                                    <span class="figma-text-dark font-bold text-sm">${pattern.hit_count}</span>
                                </div>
                            `;
                        });
                        $("#behavioralFlagsList").html(html);
                    }
                }
            } catch (err) {
                console.error("Failed to load dashboard patterns:", err);
            }
            
        } catch (error) {
            console.error("KPI load error:", error);
        }
    },
    
    getChartThemeColors() {
        const isDark = document.documentElement.getAttribute("data-theme") === "dark";
        return {
            textColor: isDark ? "#94a3b8" : "#7b8794",
            gridColor: isDark ? "rgba(255, 255, 255, 0.06)" : "rgba(0, 0, 0, 0.05)",
            accentColor: "#FF8D28",
            fillColor: isDark ? "rgba(255, 141, 40, 0.08)" : "rgba(255, 141, 40, 0.05)"
        };
    },

    updateChartColors() {
        // Handled via dashboard redraws on theme change
    },

    async initializeCharts() {
        try {
            const chartData = await API.get("/dashboard/charts");
            
            // Generate bar chart with real CSS data
            this.renderCSSBarChart(chartData);
            
            // Generate donut chart with real CSS data
            this.renderCSSDonutChart(chartData);
            
            // Keep existing Chart.js charts for other sections
            await this.renderOtherCharts(chartData);
            
        } catch (error) {
            console.error("Charts initialization error:", error);
            this.renderFallbackCharts();
        }
    },
    
    renderCSSBarChart(chartData) {
        const alertVolume = chartData.alert_volume || { dates: [], counts: [], flags: [], total_period: 0 };
        const dates = alertVolume.dates || [];
        const openCounts = alertVolume.counts || [];
        const flagCounts = alertVolume.flags || [];

        const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        const labels = dates.map(d => {
            const date = new Date(d);
            return isNaN(date.getDay()) ? d : dayNames[date.getDay()];
        });

        const totalLastPeriod = alertVolume.total_period !== undefined ? alertVolume.total_period : openCounts.reduce((a, b) => a + b, 0);
        $("#caseVolumePeriodText").text(`+${totalLastPeriod.toLocaleString()} Last period`);

        const maxVal = Math.max(...openCounts, ...flagCounts, 10);
        
        // Dynamically update Y-axis gridline labels for case volume chart
        const step = Math.ceil(maxVal / 4);
        const gridlines = $(".aml-chart .aml-gridline span");
        if (gridlines.length >= 5) {
            gridlines.eq(0).text(step * 4);
            gridlines.eq(1).text(step * 3);
            gridlines.eq(2).text(step * 2);
            gridlines.eq(3).text(step * 1);
            gridlines.eq(4).text(0);
        }

        const barsHtml = openCounts.map((openCnt, i) => {
            const darkVal = flagCounts[i] !== undefined ? flagCounts[i] : Math.round(openCnt * 0.7);
            const orangeVal = openCnt;
            
            const darkHeight = Math.min(Math.max(Math.round((darkVal / (step * 4)) * 100), 8), 95);
            const orangeHeight = Math.min(Math.max(Math.round((orangeVal / (step * 4)) * 100), 12), 95);
            
            return `
                <div class="aml-bar-group" title="Date: ${dates[i]} | Reviewed: ${darkVal} | Flagged: ${orangeVal}">
                    <div class="aml-bar dark" style="height: ${darkHeight}%;"></div>
                    <div class="aml-bar orange" style="height: ${orangeHeight}%;"></div>
                    <span class="aml-x-label">${labels[i]}</span>
                </div>
            `;
        }).join('');
        
        $("#volumeBars").html(barsHtml);
    },
    
    renderCSSDonutChart(chartData) {
        const riskCounts = chartData.risk_counts || { LOW: 0, MEDIUM: 0, HIGH: 0 };
        const lowCount = riskCounts.LOW !== undefined ? riskCounts.LOW : (chartData.risk_distribution ? chartData.risk_distribution[0] : 0);
        const mediumCount = riskCounts.MEDIUM !== undefined ? riskCounts.MEDIUM : (chartData.risk_distribution ? chartData.risk_distribution[1] : 0);
        const highCount = riskCounts.HIGH !== undefined ? riskCounts.HIGH : (chartData.risk_distribution ? chartData.risk_distribution[2] : 0);
        
        const totalRisk = lowCount + mediumCount + highCount;
        const highRiskPercentage = totalRisk > 0 ? ((highCount / totalRisk) * 100).toFixed(1) : "0.0";
        const lowMidPercentage = (100 - parseFloat(highRiskPercentage)).toFixed(1);
        
        // Update legend text dynamically with live counts
        $("#highRiskLegend").text(`High Risk - ${highCount} (${highRiskPercentage}%)`);
        $("#lowMidLegend").text(`Low/Mid - ${lowCount + mediumCount} (${lowMidPercentage}%)`);
        
        const lowMidTurn = parseFloat(lowMidPercentage) / 100;
        
        const donutStyle = `
            background: conic-gradient(
                var(--aml-dark) 0turn ${lowMidTurn}turn,
                var(--aml-orange) ${lowMidTurn}turn 1turn
            );
        `;
        
        $("#riskDonut").attr("style", donutStyle);
    },
    
    renderFallbackCharts() {
        // Simple fallback with default data
        const barsHtml = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map(day => `
            <div class="aml-bar-group">
                <div class="aml-bar dark" style="height: 30%;"></div>
                <div class="aml-bar orange" style="height: 40%;"></div>
                <span class="aml-x-label">${day}</span>
            </div>
        `).join('');
        
        $("#volumeBars").html(barsHtml);
        $("#caseVolumePeriodText").text("+350 Last period");
        
        const donutStyle = `
            background: conic-gradient(
                var(--aml-dark) 0turn 0.1turn,
                var(--aml-orange) 0.1turn 1turn
            );
        `;
        $("#riskDonut").attr("style", donutStyle);
    },
    
    async renderOtherCharts(chartData) {
        try {
            // Chart 1: Behavior Trends
            const behaviorCanvas = document.getElementById('behaviorTrendsChart');
            if (behaviorCanvas) {
                if (this.charts.behaviorTrends) {
                    this.charts.behaviorTrends.destroy();
                }

                const behaviorTrends = chartData.behavior_trends || { labels: [], detected: [], flagged: [] };
                const trendLabels = behaviorTrends.labels && behaviorTrends.labels.length > 0 ? behaviorTrends.labels : ['Feb','Mar','Apr','May','Jun','Jul'];
                const detectedData = behaviorTrends.detected || [0, 0, 0, 0, 0, 0];
                const flaggedData = behaviorTrends.flagged || [0, 0, 0, 0, 0, 0];

                this.charts.behaviorTrends = new Chart(behaviorCanvas, {
                    type: 'line',
                    data: {
                        labels: trendLabels,
                        datasets: [
                            {
                                label: 'Detected',
                                data: detectedData,
                                borderColor: '#1F2937',
                                borderWidth: 3,
                                pointBackgroundColor: '#1F2937',
                                pointRadius: 4,
                                fill: false,
                                tension: 0.3
                            },
                            {
                                label: 'Flagged',
                                data: flaggedData,
                                borderColor: '#FF8C42',
                                borderWidth: 3,
                                pointBackgroundColor: '#FF8C42',
                                pointRadius: 4,
                                fill: false,
                                tension: 0.3
                            }
                        ]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: { legend: { display: false } },
                        scales: {
                            x: {
                                grid: { display: false },
                                border: { display: false },
                                ticks: { color: '#9CA3AF', font: { size: 12, family: 'Plus Jakarta Sans' } }
                            },
                            y: {
                                grid: { color: '#f0f0f0', drawBorder: false },
                                border: { display: false },
                                ticks: { color: '#9CA3AF', font: { size: 12, family: 'Plus Jakarta Sans' } }
                            }
                        }
                    }
                });
            }

            // Chart 2: Case Status
            const caseStatusCanvas = document.getElementById('caseStatusChart');
            if (caseStatusCanvas) {
                const statusDist = chartData.status_distribution || { OPEN: 0, IN_REVIEW: 0, RESOLVED: 0, ESCALATED: 0 };
                const openVal = statusDist.OPEN || 0;
                const reviewVal = statusDist.IN_REVIEW || 0;
                const resolvedVal = statusDist.RESOLVED || 0;
                const escalatedVal = statusDist.ESCALATED || 0;

                if (this.charts.caseStatus) {
                    this.charts.caseStatus.destroy();
                }

                this.charts.caseStatus = new Chart(caseStatusCanvas, {
                    type: 'bar',
                    data: {
                        labels: ['Open', 'Review', 'Resolved', 'Escalated'],
                        datasets: [{
                            data: [openVal, reviewVal, resolvedVal, escalatedVal],
                            backgroundColor: ['#06B6D4', '#F59E0B', '#10B981', '#EF4444'],
                            borderRadius: 6,
                            barThickness: 30,
                            maxBarThickness: 40
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: { display: false },
                            tooltip: {
                                backgroundColor: '#ffffff',
                                borderColor: '#e5e7eb',
                                borderWidth: 1,
                                titleColor: '#1F2937',
                                bodyColor: '#1F2937',
                                padding: 8,
                                cornerRadius: 6,
                                callbacks: { label: (context) => `Count: ${context.parsed.y}` }
                            }
                        },
                        scales: {
                            x: {
                                grid: { display: false },
                                border: { display: false },
                                ticks: { display: true, color: '#9CA3AF', font: { size: 10, family: 'Plus Jakarta Sans' } }
                            },
                            y: {
                                grid: { display: true, color: '#f0f0f0', drawBorder: false },
                                border: { display: false },
                                ticks: { display: true, color: '#9CA3AF', font: { size: 10, family: 'Plus Jakarta Sans' } }
                            }
                        }
                    }
                });
            }

        } catch (error) {
            console.error("Chart initialization error:", error);
            showToast("error", "Failed to load charts");
        }
    },
    
    setupEventListeners() {
        // Refresh button (if added)
        $(document).on("click", ".refresh-dashboard", () => {
            this.loadDashboard();
        });
        
        // Chart resize handling
        $(window).on("resize", debounce(() => {
            Object.values(this.charts).forEach(chart => {
                if (chart && chart.resize) {
                    chart.resize();
                }
            });
        }, 250));
    },
    
    startRealTimeUpdates() {
        // Update KPIs and Charts periodically every 10 seconds
        setInterval(async () => {
            if (this.realTimeUpdates) {
                await this.loadKPIs();
                await this.initializeCharts();
            }
        }, 10000);
    },
    
    async handleNewAlert(alert) {
        // Instantly update KPIs and Charts on new alert events
        await this.loadKPIs();
        await this.initializeCharts();
    }
};

// Export for use in other modules
window.Dashboard = Dashboard;